development:
  pool: 5
  timeout: 5000
  database: db/development.sqlite3

test:
  pool: 5
  timeout: 5000
  database: db/test.sqlite3


production:
  <<: *default
  adapter: postgresql
  database: db/anikawaii.postgresql
  username: deploy
  password: chrispig1


