default: &default
adapter: postgresql
pool: 5
timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
<<: *default


production:
  <<: *default
  adapter: postgresql
  database: db/anikawaii.postgresql
  username: deploy
  password: chrispig1


