development:
  pool: 5
  timeout: 5000
  database: development.sqlite3

test:
  pool: 5
  timeout: 5000
  database: test.sqlite3


production:
  adapter: postgresql
  database: anikawaii.postgresql
  username: deploy
  password: chrispig1


